In [2]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

In [3]:
# used passenger id for index so predictions and actual survivals of test can be easily compared.  moved survive to end to split later
train = pd.read_csv("clean_train.csv", index_col='PassengerId', usecols=['PassengerId', 'Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Cabin','Embarked'])[['Pclass','Sex','Age','SibSp','Parch','Fare','Cabin','Embarked','Survived']]
train.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked  \
PassengerId                                                              
584               1    0  36.0      0      0  40.1250      7      -1.0   
476               1    0   0.0      0      0  52.0000      7       0.0   
557               1    1  48.0      1      0  39.6000      7      -1.0   
285               1    0   0.0      0      0  26.0000      7       0.0   
600               1    0  49.0      1      0  56.9292      7      -1.0   

             Survived  
PassengerId            
584                 0  
476                 0  
557                 1  
285                 0  
600                 1

In [25]:
# y = pd.factorize(train['Survived']) - unnecessary; maybe if survival was string/word
y_train = np.asarray(train['Survived'])
y_train

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [10]:
test = pd.read_csv("clean_test.csv", index_col='PassengerId', usecols=['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare','Cabin','Embarked'])[['Pclass','Sex','Age','SibSp','Parch','Fare','Cabin','Embarked']]
test.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Cabin  Embarked
PassengerId                                                           
892               3    0  34.5      0      0   7.8292      0         1
893               3    1  47.0      1      0   7.0000      0         0
894               2    0  62.0      0      0   9.6875      0         1
895               3    0  27.0      0      0   8.6625      0         0
896               3    1  22.0      1      1  12.2875      0         0

In [27]:
# used all columns for first pass
features = ['Pclass',
               'Sex',
               'Age',
               'SibSp',
               'Parch',
               'Fare',
               'Cabin',
               'Embarked']
features

['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked']

In [12]:
results = pd.read_csv('TitanicResult.csv', index_col='PassengerId')
results.head()

Survived
PassengerId          
892                 0
893                 1
894                 0
895                 0
896                 1

In [34]:
# y_results = np.asarray(results['Survived'], dtype="|S6") - did not need to switch data types
y_results = np.asarray(results['Survived'])
y_results

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [28]:
# train model
clf = RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(train[features], y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [29]:
# weighted importance of each feature
importances = clf.feature_importances_
importances

array([0.07722858, 0.24397979, 0.23213995, 0.04718   , 0.04880258,
       0.2484577 , 0.06402234, 0.03818905])

In [30]:

clf.score(train[features], y_train)

0.9741863075196409

In [31]:
predict = clf.predict(test[features])

In [35]:
# accuracy using all features
clf.score(test[features], y_results)

0.7918660287081339

In [37]:
pd.crosstab(y_results, predict, rownames=['Actual'], colnames=['Predicted'])

Predicted    0    1
Actual             
0          225   41
1           46  106